const DEFAULT_CATEGORIES = [
  {
    "id": "rx-system",
    "name": "ระบบงานจ่ายยา & คำสั่งยา",
    "icon": "Pill",
    "color": "emerald",
    "description": "ระบบสั่งยา ตรวจสอบคำสั่งยา และประวัติผู้ป่วยใน"
  },
  {
    "id": "clinical-sop",
    "name": "งานบริบาล & คู่มือการใช้ยา",
    "icon": "Stethoscope",
    "color": "teal",
    "description": "Drug Interaction, High Alert Drugs, ADR, Med Rec และแนวทางปฏิบัติ"
  },
  {
    "id": "inventory-stock",
    "name": "ระบบคลังยา & สต๊อก IPD",
    "icon": "Boxes",
    "color": "blue",
    "description": "การเบิกจ่ายยา ยายืม เบิกคลังใหญ่ และตรวจสอบสต๊อกยา"
  },
  {
    "id": "reports-stat",
    "name": "รายงาน & สถิติภาระงาน",
    "icon": "BarChart3",
    "color": "indigo",
    "description": "บันทึกสถิติประจำวัน แบบฟอร์มออนไลน์ และ Dashboard สรุปผล"
  },
  {
    "id": "external-links",
    "name": "ลิงก์ภายนอก & ติดต่อสื่อสาร",
    "icon": "Globe",
    "color": "purple",
    "description": "เว็บบอร์ด สื่อสารตึกผู้ป่วย เว็บกรม และเอกสารสำคัญ"
  }
];

const DEFAULT_LINKS = [
  {
    "id": "link-1789358634022",
    "title": "Antibiogram",
    "url": "https://drive.google.com/drive/folders/1oKJd5RtDSLyoGy3FveXLPPr-rg286MTe?usp=sharing",
    "categoryId": "rx-system",
    "badge": "Antibiogram",
    "description": "",
    "color": "amber",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "Syringe"
  },
  {
    "id": "link-1789358568302",
    "title": "เคมีบำบัด",
    "url": "http://10.0.3.201/chemotrack/pharmacy.php",
    "categoryId": "rx-system",
    "badge": "Chemotrack",
    "description": "ระบบงานเคมีบำบัด",
    "color": "purple",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "Pill"
  },
  {
    "id": "link-1789358488510",
    "title": "เอกสาร IPD",
    "url": "https://drive.google.com/drive/folders/1JQ56rchE_UJW94fVd9i25RR32H0U_IGV?usp=sharing",
    "categoryId": "clinical-sop",
    "badge": "Drug Profile",
    "description": "Drug profile และ เอกสารอื่นๆ",
    "color": "emerald",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "FileText"
  },
  {
    "id": "link-1789358343902",
    "title": "สูตรเตรียมยา",
    "url": "https://drive.google.com/drive/folders/15CTuIbuslAGrmq2hSMDKs5qO5VQY1YlD?usp=drive_link",
    "categoryId": "clinical-sop",
    "badge": "Master Formular",
    "description": "สูตรยาตา ยา extemporaneous ปรับน้ำเกลือ",
    "color": "amber",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "Pill"
  },
  {
    "id": "link-1789306098329",
    "title": "Temp IPD",
    "url": "https://suriyasuwannama.github.io/ipd-temp-dashboard/",
    "categoryId": "reports-stat",
    "badge": "TEMP IPD",
    "description": "",
    "color": "rose",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "Thermometer"
  },
  {
    "id": "link-1789302742203",
    "title": "LINE OA",
    "url": "https://account.line.biz/login?redirectUri=https%3A%2F%2Faccount.line.biz%2Foauth2%2Fcallback%3Fclient_id%3D10%26code_challenge%3DYo4BiL5PQ6XZhDba0OpUA6rQzqQeyvBq9ThukL4eRyg%26code_challenge_method%3DS256%26redirect_uri%3Dhttps%253A%252F%252Fmanager.line.biz%252Fapi%252Foauth2%252FbizId%252Fcallback%26response_type%3Dcode%26state%3DMno19KDd8yGx9jjExgF204xkinLs1RIt",
    "categoryId": "rx-system",
    "badge": "LINE OA",
    "description": "",
    "color": "emerald",
    "target": "_blank",
    "isPinned": true,
    "iconType": "preset",
    "iconValue": "MessageSquare"
  },
  {
    "id": "link-1789302349204",
    "title": "ใบรับรองเงินเดือน",
    "url": "https://statement.chiangmaihealth.go.th/web/index.php?r=site%2Flogin",
    "categoryId": "external-links",
    "badge": "SLIP",
    "description": "",
    "color": "emerald",
    "target": "_blank",
    "isPinned": false,
    "iconType": "preset",
    "iconValue": "BookOpen"
  },
  {
    "id": "link-1",
    "title": "ระบบคิวผู้ป่วย",
    "url": "https://cth-rx-queue.web.app/",
    "categoryId": "rx-system",
    "description": "",
    "iconType": "preset",
    "iconValue": "Hospital",
    "badge": "QUEUE",
    "color": "purple",
    "isPinned": true,
    "target": "_blank"
  },
  {
    "id": "link-2",
    "title": "ลงเวลาวอร์ด",
    "url": "https://docs.google.com/spreadsheets/d/1SJK581WXZqU2gjvOkyQq8YAhhDj0xmLJzloIh3m8qkI/edit?gid=1008096564#gid=1008096564",
    "categoryId": "rx-system",
    "description": "",
    "iconType": "preset",
    "iconValue": "FileText",
    "badge": "Time Sign",
    "color": "emerald",
    "isPinned": true,
    "target": "_blank"
  },
  {
    "id": "link-3",
    "title": "ํY-site compatibility",
    "url": "https://drive.google.com/file/d/1A5GIFGgA-1muWDl-qcYZJ4xJvTtytFFd/view?usp=sharing",
    "categoryId": "clinical-sop",
    "description": "",
    "iconType": "preset",
    "iconValue": "ClipboardCheck",
    "badge": "Y-site",
    "color": "teal",
    "isPinned": false,
    "target": "_blank"
  },
  {
    "id": "link-4",
    "title": "Drug Interaction & MIMS Check",
    "url": "https://www.mims.com/thailand",
    "categoryId": "clinical-sop",
    "description": "",
    "iconType": "preset",
    "iconValue": "ShieldAlert",
    "badge": "Drug Info",
    "color": "teal",
    "isPinned": false,
    "target": "_blank"
  },
  {
    "id": "link-5",
    "title": "บัญชียาโรงพยาบาลจอมทอง (CTH Formulary)",
    "url": "https://docs.google.com/spreadsheets",
    "categoryId": "clinical-sop",
    "description": "",
    "iconType": "preset",
    "iconValue": "BookOpen",
    "badge": "Formulary",
    "color": "teal",
    "isPinned": false,
    "target": "_blank"
  },
  {
    "id": "link-7",
    "title": "คลังยาผู้ป่วยใน",
    "url": "https://cth-rx-inventory.web.app/",
    "categoryId": "inventory-stock",
    "description": "",
    "iconType": "preset",
    "iconValue": "Boxes",
    "badge": "Stock",
    "color": "blue",
    "isPinned": true,
    "target": "_blank"
  },
  {
    "id": "link-9",
    "title": "จำนวนผู้ป่วยปี 2569",
    "url": "https://docs.google.com/spreadsheets/d/1el4PsjxgqWMKvaahVwahXqmVGvFT3GeTFasUuFos52s/edit?usp=share_link",
    "categoryId": "reports-stat",
    "description": "",
    "iconType": "preset",
    "iconValue": "Archive",
    "badge": "Daily Stat",
    "color": "indigo",
    "isPinned": true,
    "target": "_blank"
  },
  {
    "id": "link-10",
    "title": "ลงจำนวนเคมีบำบัด",
    "url": "https://docs.google.com/spreadsheets/d/1kFWnEEY_fa-Ho3oQuuauVvO8gE6j_xMsrb0GNl0XNzk/edit?usp=sharing",
    "categoryId": "reports-stat",
    "description": "",
    "iconType": "preset",
    "iconValue": "HeartPulse",
    "badge": "P4P Chemo",
    "color": "indigo",
    "isPinned": false,
    "target": "_blank"
  },
  {
    "id": "link-11",
    "title": "ระบบลา",
    "url": "https://smartoffice.appcth.com/smo/login?ReturnUrl=%2Fsmo",
    "categoryId": "external-links",
    "description": "",
    "iconType": "preset",
    "iconValue": "Globe",
    "badge": "SMART OFFICE",
    "color": "emerald",
    "isPinned": false,
    "target": "_blank"
  },
  {
    "id": "link-12",
    "title": "เว็บไซต์โรงพยาบาลจอมทอง",
    "url": "https://chomthonghospital.go.th",
    "categoryId": "external-links",
    "description": "เว็บบอร์ด ข่าวสาร ประกาศ และข้อมูลบุคลากร รพ.จอมทอง",
    "iconType": "preset",
    "iconValue": "Globe",
    "badge": "CTH Web",
    "color": "purple",
    "isPinned": false,
    "target": "_blank"
  }
];
